<?php

declare(strict_types=1);

# Generated by the protocol buffer compiler (for Phluxor). DO NOT EDIT!
# source: protobuf/helloworld.proto

namespace Test\ProtoBuf;

use Google\Protobuf\Internal\Message;
use Phluxor\WebSocket;

class GreeterClient extends WebSocket\BaseStub
{
    /**
     * @param HelloRequest $request
     * @param array<string|int, mixed> $metadata
     * @return HelloReply
     *
     * @throws WebSocket\Exception\InvokeException|\Exception
     */
    public function SayHello(HelloRequest $request, array $metadata = []): HelloReply // @phpcs:ignore
    {
    	return $this->serverRequest(
    	    '/helloworld.Greeter/SayHello',
            $request,
            ['\Test\ProtoBuf\HelloReply', 'decode'],
            $metadata
        );
    }
}
