<?php

declare(strict_types=1);

# Generated by the protocol buffer compiler (for Phluxor). DO NOT EDIT!
# source: protobuf/helloworld.proto

namespace Test\ProtoBuf;

use Phluxor\WebSocket;

interface GreeterInterface extends WebSocket\ServiceInterface
{
    public const string NAME = "/helloworld.Greeter";

    /**
     * @param WebSocket\ContextInterface $ctx
     * @param WebSocket\Stream $stream
     * @return void
     *
     * @throws WebSocket\Exception\InvokeException
     */
    public function SayHello(WebSocket\ContextInterface $ctx, WebSocket\Stream $stream): void; // @phpcs:ignore
}
