<?php

declare(strict_types=1);

# Generated by the protocol buffer compiler (for Phluxor). DO NOT EDIT!
# source: protobuf/helloworld.proto

namespace Test\ProtoBuf;

use Phluxor\WebSocket;

interface GreeterInterface extends WebSocket\ServiceInterface
{
    public const string NAME = "/helloworld.Greeter";

    /**
     * @param WebSocket\ContextInterface $ctx
     * @param HelloRequest $request
     * @return HelloReply
     *
     * @throws WebSocket\Exception\InvokeException
     */
    public function SayHello(WebSocket\ContextInterface $ctx, HelloRequest $request): HelloReply; // @phpcs:ignore
}
