<?php

declare(strict_types=1);

# Generated by the protocol buffer compiler (for Phluxor). DO NOT EDIT!
# source: protobuf/helloworld.proto

namespace Test\ProtoBuf;

use Phluxor\WebSocket;

class StreamService implements StreamInterface
{
    /**
     * @param WebSocket\ContextInterface $ctx
     * @param HelloRequest $request
     * @return HelloReply
     *
     * @throws WebSocket\Exception\InvokeException
     */
    public function FetchResponse(WebSocket\ContextInterface $ctx, HelloRequest $request): HelloReply // @phpcs:ignore
    {
        $name = $request->getName();
        $out = new HelloReply();
        $out->setMessage('hello ' . $name . time());
        $message = new WebSocket\Message($ctx, $out);
        $ctx[WebSocket\Constant::SERVER_WORKER_CONTEXT]->getValue(WebSocket\Server::class)->push($message);
        return $out;
    }
}
